version: '3'

services:
  proxy:
    ports:
      - "8080:80"
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    networks: 
      - mynetwork
    depends_on: 
      - app

  app:
    build: 
      context: ./node
      dockerfile: Dockerfile
    working_dir: /home/node/app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: sh -c "yarn start"
    depends_on: 
      - db
    networks: 
      - mynetwork

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    networks: 
      - mynetwork

networks: 
  mynetwork:
    driver: bridge
